trigger: none
pr: none

# Pipeline resource defined as per https://bit.ly/3PhwhRk
resources:
  pipelines:
  - pipeline: build_pipeline        # Used to reference the pipeline reference from other parts of the code.
    source: build_pipeline  	# This must match  the build pipeline name in ADO.
                                    # By default, pipelines are named after the ADO build pipeline name.
    trigger:
      branches:
      - master                      # Will get triggered whenever the source pipeline runs on master branch.

jobs:
- deployment: sparkrosedigital_template_deploy_to_appservice
  displayName: SparkRoseDigital_Template Deploy to AppService
  environment: production
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          displayName: 'Create version number'
          name: 'CreateVersionNumber'
          inputs:
            targetType: 'inline'
            script: |
              $newVersion = "$(resources.pipeline.build_pipeline.runName)"
              [string] $buildName = "$($newVersion)"
              Write-Host "##vso[build.updatebuildnumber]$buildName"

        - download: none

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact SparkRoseDigital_Template.Api'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.SparkRoseDigital_Template.Api'
            project: 'SparkRoseDigital_Template_ADO_Project'
            downloadPath: '$(Pipeline.Workspace)/drop/SparkRoseDigital_Template.Api'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact SparkRoseDigital_Template.WorkerServices'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.SparkRoseDigital_Template.WorkerServices'
            project: 'SparkRoseDigital_Template_ADO_Project'
            downloadPath: '$(Pipeline.Workspace)/drop/SparkRoseDigital_Template.WorkerServices'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact SparkRoseDigital_Template.Migrations'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.SparkRoseDigital_Template.Migrations'
            project: 'SparkRoseDigital_Template_ADO_Project'
            downloadPath: '$(Pipeline.Workspace)/drop/SparkRoseDigital_Template.Migrations'

        - script: dotnet $(Pipeline.Workspace)/drop/SparkRoseDigital_Template.Migrations/SparkRoseDigital_Template.Migrations.dll "$(ConnectionStrings__SparkRoseDigital_TemplateDb_Migrations_Connection)" "$(DB_USER)" "$(DB_PASSWORD)" "$(Pipeline.Workspace)/drop/SparkRoseDigital_Template.Migrations"
          displayName: 'Migrate database'

        - task: AzureWebApp@1
          displayName: 'Deploy SparkRoseDigital_Template.Api to App Service'
          inputs:
            azureSubscription: 'AzureConnection_SparkRoseDigital_Template'
            appType: 'webAppLinux'
            appName: '$(app_service_web_name)'
            resourceGroupName: '$(rg)'
            package: '$(Pipeline.Workspace)/drop/SparkRoseDigital_Template.Api/**/*.zip'
            runtimeStack: 'DOTNETCORE|6.0'
