trigger: none
pr: none

# Pipeline resource defined as per https://bit.ly/3PhwhRk
resources:
  pipelines:
  - pipeline: build_pipeline        # Used to reference the pipeline reference from other parts of the code.
    source: build_pipeline  	# This must match  the build pipeline name in ADO.
                                    # By default, pipelines are named after the ADO build pipeline name.
    trigger:
      branches:
      - master                      # Will get triggered whenever the source pipeline runs on master branch.

jobs:
- deployment: sparkrosedigital_deploy_to_appservice
  displayName: SparkRoseDigital Deploy to AppService
  environment: production
  variables:
    adoProject: 'SparkRoseDigital'
    azureServiceConnection: 'AzureConnection_SparkRoseDigital'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          fetchDepth: 0

        - script: pwd
          displayName: 'Basic Information - pwd'

        - script: ls -al
          displayName: 'Basic Information - Directory Contents'

        - task: PowerShell@2
          displayName: 'Create version number'
          name: 'CreateVersionNumber'
          inputs:
            targetType: 'inline'
            script: |
              $newVersion = "$(resources.pipeline.build_pipeline.runName)"
              [string] $buildName = "$($newVersion)"
              Write-Host "##vso[build.updatebuildnumber]$buildName"

        - download: none

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact SparkRoseDigital.Api'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.SparkRoseDigital.Api'
            project: '$(adoProject)'
            downloadPath: '$(Pipeline.Workspace)/drop/SparkRoseDigital.Api'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact SparkRoseDigital.WorkerServices'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.SparkRoseDigital.WorkerServices'
            project: '$(adoProject)'
            downloadPath: '$(Pipeline.Workspace)/drop/SparkRoseDigital.WorkerServices'

        - task: DownloadPipelineArtifact@2
          displayName: 'Download Artifact SparkRoseDigital.Migrations'
          inputs:
            buildType: 'specific'
            definition: build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop.SparkRoseDigital.Migrations'
            project: '$(adoProject)'
            downloadPath: '$(Pipeline.Workspace)/drop/SparkRoseDigital.Migrations'

        - task: AzureCLI@2
          displayName: 'Entra Api Registration'
          name: 'entraApiRegistration'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/entraApiRegistration.ps1'
            arguments: '$(PROJECT_NAME) $env:tenantId'
            powerShellErrorActionPreference: stop
            addSpnToEnvironment: true
        
        - task: AzureCLI@2
          displayName: 'Provision Resource Group'
          name: 'provisionResourceGroup'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/provisionResourceGroup.ps1'
            arguments: '$(LOCATION) $(ENVIRONMENT) $(PROJECT_NAME)'
            powerShellErrorActionPreference: stop
        
        - task: AzureCLI@2
          displayName: 'Provision Resources'
          name: 'provisionResources'
          inputs:
            azureSubscription: 'AzureConnection'
            scriptType: pscore
            scriptLocation: 'scriptPath'
            scriptPath: './deployment/provisionResources.ps1'
            arguments: '$(ENVIRONMENT) $(PROJECT_NAME) $(provisionResourceGroup.resourceGroupName) $(DB_USER) $(DB_PASSWORD) $(entraApiRegistration.authAuthority) $(entraApiRegistration.authAudience) $(entraApiRegistration.authValidIssuer)'
            powerShellErrorActionPreference: stop

        - script: dotnet $(Pipeline.Workspace)/drop/SparkRoseDigital.Migrations/SparkRoseDigital.Migrations.dll "$(provisionResources.dbConnection)" "$(DB_USER)" "$(DB_PASSWORD)" "$(Pipeline.Workspace)/drop/SparkRoseDigital.Migrations"
          displayName: 'Migrate database'

        - task: AzureWebApp@1
          displayName: 'Deploy SparkRoseDigital.Api to App Service'
          inputs:
            azureSubscription: 'AzureConnection'
            appType: 'webAppLinux'
            appName: '$(provisionResources.appServiceWebName)'
            resourceGroupName: '$(provisionResourceGroup.resourceGroupName)'
            package: '$(Pipeline.Workspace)/drop/SparkRoseDigital.Api/**/*.zip'
            runtimeStack: 'DOTNETCORE|6.0'
