version: '3.7'

services:
  sparkrosedigital_template.migrations:
    # image: ${DOCKER_REGISTRY-}sparkrosedigital_templatesql
    env_file: .env
    build:
      context: .
      dockerfile: src/SparkRoseDigital_Template.Migrations/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"